# Device trees for Google Tensor (Samsung Exynos derived) SoCs.

DTS=	\
	exynos/google/zumapro-caiman.dts	\
	exynos/google/zumapro-comet.dts		\
	exynos/google/zumapro-komodo.dts	\
	exynos/google/zumapro-tegu.dts		\
	exynos/google/zumapro-tokay.dts

.include <bsd.dtb.mk>
